# Generated by Django 2.0.1 on 2020-06-22 13:20

from django.conf import settings
from django.db import migrations
import django_resized.forms
import django_utils.choices
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_auto_20200621_1352'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostComments',
            new_name='PostComment',
        ),
        migrations.AlterField(
            model_name='company',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, django_utils.choices.Choice(1, 'Послуги')), (2, django_utils.choices.Choice(2, 'Дозвілля')), (3, django_utils.choices.Choice(3, 'Одяг')), (4, django_utils.choices.Choice(4, 'Продукти')), (5, django_utils.choices.Choice(5, 'Виробництво')), (6, django_utils.choices.Choice(6, "Здоров'я"))], default=None, max_length=11),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, null=True, quality=100, size=[150, 150], upload_to='companies/logos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, null=True, quality=100, size=[150, 150], upload_to='customers/avatars/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, django_utils.choices.Choice(1, 'Послуги')), (2, django_utils.choices.Choice(2, 'Дозвілля')), (3, django_utils.choices.Choice(3, 'Одяг')), (4, django_utils.choices.Choice(4, 'Продукти')), (5, django_utils.choices.Choice(5, 'Виробництво')), (6, django_utils.choices.Choice(6, "Здоров'я"))], default=None, max_length=11),
        ),
        migrations.AlterField(
            model_name='postimages',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, null=True, quality=100, size=[1000, 1000], upload_to='posts/pictures/%Y/%m/%d'),
        ),
    ]
